// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	context "context"

	processor "github.com/kordape/ottct-poller-service/internal/processor"
	mock "github.com/stretchr/testify/mock"
)

// TweetsFetcher is an autogenerated mock type for the TweetsFetcher type
type TweetsFetcher struct {
	mock.Mock
}

// FetchTweets provides a mock function with given fields: _a0, _a1
func (_m *TweetsFetcher) FetchTweets(_a0 context.Context, _a1 processor.FetchTweetsRequest) (processor.FetchTweetsResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 processor.FetchTweetsResponse
	if rf, ok := ret.Get(0).(func(context.Context, processor.FetchTweetsRequest) processor.FetchTweetsResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(processor.FetchTweetsResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, processor.FetchTweetsRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type NewTweetsFetcherT interface {
	mock.TestingT
	Cleanup(func())
}

// NewTweetsFetcher creates a new instance of TweetsFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTweetsFetcher(t NewTweetsFetcherT) *TweetsFetcher {
	mock := &TweetsFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
